GET https://jsonplaceholder.typicode.com/posts/1
###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Mein erster Post",
  "body": "Das ist ein Test.",
  "userId": 10
}